import { Typography } from '@mui/material';
import React from 'react';
import { BrandsSlip, Overlay, SliderWrapper, Wrapper } from './Brands.style';
import { motion } from 'framer-motion';

const Brands = () => {
   return (
      <Wrapper>
         <Typography
            variant='h4'
            sx={{
               fontWeight: '700',
               px: '1rem',
               '@media (min-width: 600px)': {
                  display: 'none',
               },
            }}
         >
            Our Product Brands
         </Typography>
         <Overlay>
            <Typography variant='h3' sx={{ fontWeight: '800', color: 'white' }}>
               Our Product Brands
            </Typography>
         </Overlay>
         <SliderWrapper>
            <BrandsSlip
               component={motion.div}
               animate={{ x: -9912 }}
               transition={{
                  repeat: Infinity,
                  duration: 220,
                  type: 'linear',
                  ease: 'linear',
               }}
            >
               <img
                  src='https://solruf.s3.ap-south-1.amazonaws.com/Adani_.png'
                  alt=''
               />
               <img
                  src={
                     'https://solruf.s3.ap-south-1.amazonaws.com/Contendre+Solar.png'
                  }
                  alt=''
               />
               <img src={'https://i.ibb.co/6ZLJZf6/image-95.png'} alt='' />
               <img
                  src={'https://solruf.s3.ap-south-1.amazonaws.com/Growatt.png'}
                  alt=''
               />
               <img
                  src={'https://solruf.s3.ap-south-1.amazonaws.com/Jakson.png'}
                  alt=''
               />
               <img
                  src={
                     'https://solruf.s3.ap-south-1.amazonaws.com/Jinko+Solar.png'
                  }
                  alt=''
               />
               <img src={'https://i.ibb.co/3zD38Pd/image-96.png'} alt='' />
               <img
                  src={
                     'https://solruf.s3.ap-south-1.amazonaws.com/Luminous.png'
                  }
                  alt=''
               />
               <img
                  src={
                     'https://solruf.s3.ap-south-1.amazonaws.com/Pataanjali.png'
                  }
                  alt=''
               />
               <img
                  src={
                     'https://solruf.s3.ap-south-1.amazonaws.com/RenewSys.png'
                  }
                  alt=''
               />
               <img
                  src={'https://solruf.s3.ap-south-1.amazonaws.com/Saatvik.png'}
                  alt=''
               />
               <img
                  src={'https://solruf.s3.ap-south-1.amazonaws.com/Solis_.png'}
                  alt=''
               />
               <img
                  src={'https://solruf.s3.ap-south-1.amazonaws.com/Sungrow.png'}
                  alt=''
               />
               <img
                  src={
                     'https://solruf.s3.ap-south-1.amazonaws.com/Trina+Solar.png'
                  }
                  alt=''
               />
               <img
                  src={
                     'https://solruf.s3.ap-south-1.amazonaws.com/Vikram+Solar.png'
                  }
                  alt=''
               />
               <img
                  src={'https://solruf.s3.ap-south-1.amazonaws.com/WAAREE.png'}
                  alt=''
               />
               <img
                  src={
                     'https://solruf.s3.ap-south-1.amazonaws.com/loom+Solar.png'
                  }
                  alt=''
               />
               <img
                  src='https://solruf.s3.ap-south-1.amazonaws.com/Adani_.png'
                  alt=''
               />
               <img
                  src={
                     'https://solruf.s3.ap-south-1.amazonaws.com/Contendre+Solar.png'
                  }
                  alt=''
               />
               <img src={'https://i.ibb.co/6ZLJZf6/image-95.png'} alt='' />
               <img
                  src={'https://solruf.s3.ap-south-1.amazonaws.com/Growatt.png'}
                  alt=''
               />
               <img
                  src={'https://solruf.s3.ap-south-1.amazonaws.com/Jakson.png'}
                  alt=''
               />
               <img
                  src={
                     'https://solruf.s3.ap-south-1.amazonaws.com/Jinko+Solar.png'
                  }
                  alt=''
               />
               <img src={'https://i.ibb.co/3zD38Pd/image-96.png'} alt='' />
               <img
                  src={
                     'https://solruf.s3.ap-south-1.amazonaws.com/Luminous.png'
                  }
                  alt=''
               />
               <img
                  src={
                     'https://solruf.s3.ap-south-1.amazonaws.com/Pataanjali.png'
                  }
                  alt=''
               />
               <img
                  src={
                     'https://solruf.s3.ap-south-1.amazonaws.com/RenewSys.png'
                  }
                  alt=''
               />
               <img
                  src={'https://solruf.s3.ap-south-1.amazonaws.com/Saatvik.png'}
                  alt=''
               />
               <img
                  src={'https://solruf.s3.ap-south-1.amazonaws.com/Solis_.png'}
                  alt=''
               />
               <img
                  src={'https://solruf.s3.ap-south-1.amazonaws.com/Sungrow.png'}
                  alt=''
               />
               <img
                  src={
                     'https://solruf.s3.ap-south-1.amazonaws.com/Trina+Solar.png'
                  }
                  alt=''
               />
               <img
                  src={
                     'https://solruf.s3.ap-south-1.amazonaws.com/Vikram+Solar.png'
                  }
                  alt=''
               />
               <img
                  src={'https://solruf.s3.ap-south-1.amazonaws.com/WAAREE.png'}
                  alt=''
               />
               <img
                  src={
                     'https://solruf.s3.ap-south-1.amazonaws.com/loom+Solar.png'
                  }
                  alt=''
               />
               <img
                  src='https://solruf.s3.ap-south-1.amazonaws.com/Adani_.png'
                  alt=''
               />
               <img
                  src={
                     'https://solruf.s3.ap-south-1.amazonaws.com/Contendre+Solar.png'
                  }
                  alt=''
               />
               <img src={'https://i.ibb.co/6ZLJZf6/image-95.png'} alt='' />
               <img
                  src={'https://solruf.s3.ap-south-1.amazonaws.com/Growatt.png'}
                  alt=''
               />
               <img
                  src={'https://solruf.s3.ap-south-1.amazonaws.com/Jakson.png'}
                  alt=''
               />
               <img
                  src={
                     'https://solruf.s3.ap-south-1.amazonaws.com/Jinko+Solar.png'
                  }
                  alt=''
               />
               <img src={'https://i.ibb.co/3zD38Pd/image-96.png'} alt='' />
               <img
                  src={
                     'https://solruf.s3.ap-south-1.amazonaws.com/Luminous.png'
                  }
                  alt=''
               />
               <img
                  src={
                     'https://solruf.s3.ap-south-1.amazonaws.com/Pataanjali.png'
                  }
                  alt=''
               />
               <img
                  src={
                     'https://solruf.s3.ap-south-1.amazonaws.com/RenewSys.png'
                  }
                  alt=''
               />
               <img
                  src={'https://solruf.s3.ap-south-1.amazonaws.com/Saatvik.png'}
                  alt=''
               />
               <img
                  src={'https://solruf.s3.ap-south-1.amazonaws.com/Solis_.png'}
                  alt=''
               />
               <img
                  src={'https://solruf.s3.ap-south-1.amazonaws.com/Sungrow.png'}
                  alt=''
               />
               <img
                  src={
                     'https://solruf.s3.ap-south-1.amazonaws.com/Trina+Solar.png'
                  }
                  alt=''
               />
               <img
                  src={
                     'https://solruf.s3.ap-south-1.amazonaws.com/Vikram+Solar.png'
                  }
                  alt=''
               />
               <img
                  src={'https://solruf.s3.ap-south-1.amazonaws.com/WAAREE.png'}
                  alt=''
               />
               <img
                  src={
                     'https://solruf.s3.ap-south-1.amazonaws.com/loom+Solar.png'
                  }
                  alt=''
               />
               <img
                  src='https://solruf.s3.ap-south-1.amazonaws.com/Adani_.png'
                  alt=''
               />
               <img
                  src={
                     'https://solruf.s3.ap-south-1.amazonaws.com/Contendre+Solar.png'
                  }
                  alt=''
               />
               <img src={'https://i.ibb.co/6ZLJZf6/image-95.png'} alt='' />
               <img
                  src={'https://solruf.s3.ap-south-1.amazonaws.com/Growatt.png'}
                  alt=''
               />
               <img
                  src={'https://solruf.s3.ap-south-1.amazonaws.com/Jakson.png'}
                  alt=''
               />
               <img
                  src={
                     'https://solruf.s3.ap-south-1.amazonaws.com/Jinko+Solar.png'
                  }
                  alt=''
               />
               <img src={'https://i.ibb.co/3zD38Pd/image-96.png'} alt='' />
               <img
                  src={
                     'https://solruf.s3.ap-south-1.amazonaws.com/Luminous.png'
                  }
                  alt=''
               />
               <img
                  src={
                     'https://solruf.s3.ap-south-1.amazonaws.com/Pataanjali.png'
                  }
                  alt=''
               />
               <img
                  src={
                     'https://solruf.s3.ap-south-1.amazonaws.com/RenewSys.png'
                  }
                  alt=''
               />
               <img
                  src={'https://solruf.s3.ap-south-1.amazonaws.com/Saatvik.png'}
                  alt=''
               />
               <img
                  src={'https://solruf.s3.ap-south-1.amazonaws.com/Solis_.png'}
                  alt=''
               />
               <img
                  src={'https://solruf.s3.ap-south-1.amazonaws.com/Sungrow.png'}
                  alt=''
               />
               <img
                  src={
                     'https://solruf.s3.ap-south-1.amazonaws.com/Trina+Solar.png'
                  }
                  alt=''
               />
               <img
                  src={
                     'https://solruf.s3.ap-south-1.amazonaws.com/Vikram+Solar.png'
                  }
                  alt=''
               />
               <img
                  src={'https://solruf.s3.ap-south-1.amazonaws.com/WAAREE.png'}
                  alt=''
               />
               <img
                  src={
                     'https://solruf.s3.ap-south-1.amazonaws.com/loom+Solar.png'
                  }
                  alt=''
               />
            </BrandsSlip>
         </SliderWrapper>
      </Wrapper>
   );
};

export default Brands;
